### ISSUE TITLE
为什么会出现文件未找到异常

### ISSUE THREAD

**Issue by ChenHauShen** [to2mbn/authlib-injector#3]
![image](https://user-images.githubusercontent.com/18183312/33662225-08de48d2-dac6-11e7-92f5-d9c25b36c297.png)

[authlib-injector] unable to configure remotely: java.io.FileNotFoundException: http://10.0.0.100:50001/yggdrasil-backend-0.0.1-SNAPSHOT/yggdrasil
java.io.UncheckedIOException: java.io.FileNotFoundException: no config is found
        at org.to2mbn.authlibinjector.AuthlibInjector.loadConfig(AuthlibInjector.java:59)
        at org.to2mbn.authlibinjector.AuthlibInjector.bootstrap(AuthlibInjector.java:39)
        at org.to2mbn.authlibinjector.javaagent.AuthlibInjectorPremain.premain(AuthlibInjectorPremain.java:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.io.FileNotFoundException: no config is found
        at org.to2mbn.authlibinjector.AuthlibInjector.lookupConfig(AuthlibInjector.java:83)
        at org.to2mbn.authlibinjector.AuthlibInjector.loadConfig(AuthlibInjector.java:55)
        ... 8 more

**Comment by yushijinhun** [comment]
这说明请求这个URL返回的是HTTP 404。
需要注意的是authlib-injector和authlib-agent项目**不兼容**。
